# Generated by Django 2.1.7 on 2019-03-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='url',
            new_name='api_url',
        ),
        migrations.AddField(
            model_name='user',
            name='html_url',
            field=models.CharField(default='', max_length=50),
        ),
    ]
