# Generated by Django 2.1.7 on 2019-03-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh_api', '0002_auto_20190311_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='blog',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='html_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
