# Generated by Django 2.1.7 on 2019-03-11 02:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gh_api', '0003_auto_20190311_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
